import fs from 'fs';
import path from 'path';

export async function run(context, args) {
  const ai = context.aiClient;
  const gitlab = context.gitlabClient;
  const tenantId = context.config.tenantId || 'default';
  
  if (!ai) {
    return { output: 'Error: AI client not configured.' };
  }
  
  const prompt = args.join(' ');
  
  if (!prompt) {
    return { output: 'Usage: asro generate plugin <description>' };
  }
  
  const pluginName = prompt.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  
  const systemPrompt = `You are a DevSecOps plugin generator. Generate a plugin for ASRO CLI based on this description: "${prompt}"

Return ONLY valid JavaScript code for the plugin. The plugin should export:
{
  name: "${pluginName}",
  commands: {
    [commandName]: async (context, args) => {
      return { success: true, output: "..." };
    }
  }
}

Make it production-ready with proper error handling.`;
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: systemPrompt,
      config: { responseMimeType: 'text/plain' }
    });
    
    const pluginCode = response.text;
    
    const pluginDir = path.join(process.cwd(), '.asro', 'plugins', pluginName);
    fs.mkdirSync(pluginDir, { recursive: true });
    
    const pluginIndexPath = path.join(pluginDir, 'index.js');
    fs.writeFileSync(pluginIndexPath, pluginCode);
    
    const readmePath = path.join(pluginDir, 'README.md');
    fs.writeFileSync(readmePath, `# ${pluginName}\n\nGenerated by ASRO AI\n\n## Description\n${prompt}\n`);
    
    let repoUrl = '';
    if (gitlab) {
      try {
        const projectId = context.config.gitlabProjectId;
        repoUrl = `https://gitlab.com/${projectId}/-/tree/main/.asro/plugins/${pluginName}`;
      } catch (e) {
        console.warn('Could not create GitLab repo link');
      }
    }
    
    return {
      output: `[SUCCESS] Plugin "${pluginName}" created at ${pluginDir}\n${repoUrl ? `Repository: ${repoUrl}` : ''}\n\nUse: asro ${pluginName} <command>`,
      data: { name: pluginName, path: pluginDir, repoUrl }
    };
  } catch (error) {
    return { output: `Error generating plugin: ${error.message}` };
  }
}